ALTER TABLE users ADD COLUMN deleted_at TIMESTAMP NULL;
ALTER TABLE tournaments ADD COLUMN deleted_at TIMESTAMP NULL;
ALTER TABLE leagues ADD COLUMN deleted_at TIMESTAMP NULL;
ALTER TABLE reservations ADD COLUMN deleted_at TIMESTAMP NULL;

