openapi: 3.0.3
info:
  title: ThePaddlersApp API
  version: 1.0.0
  description: OpenAPI spec for backend endpoints
servers:
  - url: https://api.thepaddlers.com
paths:
  /api/webhooks/stripe:
    post:
      summary: Stripe webhook endpoint
      description: Receives Stripe events, verifies signature, and processes payment events
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
      responses:
        '200':
          description: Event processed
        '400':
          description: Invalid signature or missing header
        '500':
          description: Internal error
      parameters:
        - name: Stripe-Signature
          in: header
          required: false
          schema:
            type: string
  /api/bookings:
    post:
      summary: Create a booking
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Booking'
      responses:
        '201':
          description: Booking created
        '409':
          description: Time slot conflict
    get:
      summary: List bookings
      responses:
        '200':
          description: List of bookings
  /api/bookings/{id}:
    get:
      summary: Get booking by ID
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Booking details
        '404':
          description: Not found
components:
  schemas:
    Booking:
      type: object
      properties:
        id:
          type: integer
        court:
          type: object
          properties:
            id:
              type: integer
            name:
              type: string
        user:
          type: object
          properties:
            id:
              type: integer
            name:
              type: string
            email:
              type: string
        startAt:
          type: string
          format: date-time
        endAt:
          type: string
          format: date-time
        status:
          type: string

